version: '3.4'

x-cache:
  &cache
  cache_from:
    - ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}-php
    - ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}-nginx
    - ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}-varnish
    - ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}-admin
    - ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}-client
    - ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}-h2-proxy

services:
  php:
    &php
    image: ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}-php:${APP_ENV}
    build:
      context: ./api
      target: api_platform_php
      <<: *cache
    depends_on:
      - db
    volumes:
      - ./api:/srv/api:rw,cached
      # If you develop on Linux, uncomment the following line to use a bind-mounted host directory instead
      # - ./api/var:/srv/api/var:rw
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG} 
      - APP_VERSION=${CONTAINER_PROJECT_VERSION}     
      - APP_TITLE=${CONTAINER_PROJECT_TITLE}
      - APP_NAME=${CONTAINER_PROJECT_NAME}
      - DATABASE_URL=postgres://api-platform:!ChangeMe!@db/api?serverVersion=10.1

  api:
    image: ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}-nginx
    build:
      context: ./api
      target: api_platform_nginx
      <<: *cache
    depends_on:
      - php
    # Comment out this volume in production
    volumes:
      - ./api/public:/srv/api/public:ro
    ports:
      - "8080:80"

  cache-proxy:
    &varnish
    image: ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}-varnish:${APP_ENV}
    build:
      context: ./api
      target: api_platform_varnish
      <<: *cache
    depends_on:
      - api
    volumes:
      - ./api/docker/varnish/conf:/usr/local/etc/varnish:ro
    tmpfs:
      - /usr/local/var/varnish:exec
    ports:
      - "8081:80"
    environment:
      - APP_ENV=${APP_ENV}
      - APP_NAME=${CONTAINER_PROJECT_NAME}
  db:
    # In production, you may want to use a managed database service
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=api-platform
      # You should definitely change the password in production
      - POSTGRES_PASSWORD=!ChangeMe!
    volumes:
      - dev-db-data:/var/lib/postgresql/data:rw

  mercure:
    # In production, you may want to use the managed version of Mercure, https://mercure.rocks
    image: dunglas/mercure
    environment:
      # You should definitely change all these values in production
      - JWT_KEY=!UnsecureChangeMe!
      - ALLOW_ANONYMOUS=1
      - CORS_ALLOWED_ORIGINS=*
      - PUBLISH_ALLOWED_ORIGINS=http://localhost:1337,https://localhost:1338
      - DEMO=1
    ports:
      - "1337:80"

  client:
    # Use a static website hosting service in production
    # See https://facebook.github.io/create-react-app/docs/deployment
    image: ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}-client
    build:
      context: ./client
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/client
    env_file:
      - ./client/.env
    volumes:
      - ./client:/usr/src/client:rw,cached
      - /usr/src/client/node_modules

  admin:
    # Use a static website hosting service in production
    # See https://facebook.github.io/create-react-app/docs/deployment
    image: ${CONTAINER_REGISTRY_BASE}/admin
    build:
      context: ./admin
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}-admin
    volumes:
      - ./admin:/usr/src/admin:rw,cached
      - /usr/src/admin/node_modules

  h2-proxy:
    # Don't use this proxy in prod
    build:
      context: ./h2-proxy
      cache_from:
        - ${CONTAINER_REGISTRY_BASE}/${CONTAINER_PROJECT_NAME}-h2-proxy
    depends_on:
      - client
      - admin
      - api
      - cache-proxy
      - mercure
      #- stag-pc-cache-proxy
      #- dev-pc-cache-proxy
    #volumes:
    #  - ./conf.d/:/etc/nginx/conf.d/:rw,cached
    ports:
      - "80:80" #http port
      - "443:443" #ssl port
      - "444:444"
      - "8443:8443"
      - "8444:8444" 
      - "5432:5432" #postgress port
    environment:
      - APP_ENV=${APP_ENV}
      - APP_NAME=${CONTAINER_PROJECT_NAME}

volumes:
  prod-db-data: {}
  stag-db-data: {}
  dev-db-data: {}
