apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ include "name" . }}-{{ .Values.settings.env }}-nginx
  labels:
    app.kubernetes.io/name: {{ include "name" . }}-{{ .Values.settings.env }}-nginx
    app.kubernetes.io/part-of: {{ include "name" . }}-{{ .Values.settings.env }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}-{{ .Values.settings.env }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "name" . }}-{{ .Values.settings.env }}-nginx
        app.kubernetes.io/part-of: {{ include "name" . }}-{{ .Values.settings.env }}
        helm.sh/chart: {{ include "chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}-{{ .Values.settings.env }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ include "name" . }}-{{ .Values.settings.env }}-nginx
          image: "{{ .Values.settings.registryBase }}/{{ .Values.settings.projectName }}-nginx:{{ .Values.settings.env }}"
          imagePullPolicy: {{ .Values.settings.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: PHP_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: {{ template "fullname" . }}
                  key: php-service
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
